# params config
# iter params
batch_size:    128
epoch:        5
learn_rate:    0.01
log_train_batch:  25  # 每隔几个batch在tensorboard里记录训练信息
eval_test_batch:  100  # 每隔几个batch评估一下切分出来的测试集
early_stop_eval_n:  8000  # 每隔几次评估后，eval_acc不出现增长就早停止
model_dir:     '../docs/model/'
model_name:    'best'
# model_type:    'CNN-non-static' # only CNN-static, CNN-non-static, CNN-rand valiable

# data prarms
dropout: 0.9
num_classes: 2
max_document_length: 100
title_dim:  0 # just placeholder
content_dim:  0 # just placeholder
combine_dim:  0 # just placeholder
vocab_size: 0 # just placeholder
sent_len:   50
sent_num:    100
embedding_size:  128
label:
  dim: 2
  loss_weight:    1 # not use now
  loss_activate:  'sigmoid' # only sigmoid, softmax
  loss_func:  'binary_crossentropy' # only binary_crossentropy, categorical_crossentropy
  W_regularizer: 0.1
  activity_reg: {l1: 0.1}
#  batch_norm: {momentum: 0.9}
# layer params
conv1D:
    layer1:
        filters:       48
        filter_size:    128 #embedding_size  #default 2
        padding_mode:   'same'
        pooling_size:  2 # default 2
        dropout:       0.5
        batch_norm:    0.9
    layer2:
        filters:       48
        filter_size:   2
        padding_mode:   'same'
        pooling_size:  2 # default 2
        dropout:      0.5
        batch_norm:   0.9
        activation:   'relu'

    layer3:
        filters:       96
        filter_size:   3
        padding_mode:   'same'
#        pooling_size:  2 # default 2
        dropout:      0.2
        batch_norm:   0.9
    layer4:
        filters:       128
        filter_size:   3
        padding_mode:   'same'
        pooling_size:  2 # default 2
#        dropout:      0.2
        batch_norm:   0.9
        activation:   'relu'

    layer5:
        filters:       128
        filter_size:   5
        padding_mode:   'same'
#        pooling_size:  2 # default 2
#        dropout:      0.2
        batch_norm:   0.9
    layer6:
        filters:       128
        filter_size:   5
        padding_mode:   'same'
        pooling_size:  2 # default 2
#        dropout:      0.2
        batch_norm:   0.9
        activation:   'relu'

RNN:
    cell: 256
#    dropout: 0.2  # default 0.
#    recurrent_dropout: 0.1  # default 0.
    merge_mode: 'concat'  # One of {'sum', 'mul', 'concat', 'ave', None}
    batch_norm: 0.9